meal_plans/urls.py
from django.urls import path


from meal_plans.views import (
    MealPlanListView,
    MealPlanDeleteView,
    MealPlanUpdateView,
    MealPlanDetailView,
    MealPlanCreateView,
)

urlpatterns = [
    path("", MealPlanListView.as_view(), name="meal_plans_list"),
    path("create/", MealPlanCreateView.as_view(), name="meal_plans_new"),
    path("<int:pk>/", MealPlanDeleteView.as_view(), name="meal_plans_delete"),
    path("<int:pk>/edit/", MealPlanDetailView.as_view(), name="meal_plans_detail"),
    path("<int:pk>/delete/", MealPlanUpdateView.as_view(), name="meal_plans_edit"),

]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("meal_plans/", include("meal_plans.urls")),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings
USER_MODEL = settings.AUTH_USER_MODEL


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField()
    owner = models.ForeignKey(
        USER_MODEL,
        on_delete=models.CASCADE,
    )
    recipes = models.ManyToManyField(
        "recipes.Recipe", related_name="meal_plans")

meal_plans/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from meal_plans.models import MealPlan


class MealPlanListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 2

    def get_queryset(self):
        return MealPlan.objects.filter(owner_id=self.request.user)


class MealPlanDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["rating_form"] = RatingForm()
    #     return context


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "recipes", "date"]
    success_url = reverse_lazy("meal_plans_list")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plans_detail", pk=plan.id)


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name", "owner"]
    success_url = reverse_lazy("recipes_list")


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meal_plans_list")







# from django.shortcuts import redirect
# from django.urls import reverse_lazy
# from django.views.generic import ListView
# from django.views.generic import DetailView
# from django.views.generic import CreateView, DeleteView, UpdateView
# from django.contrib.auth.mixins import LoginRequiredMixin
# from meal_plans.models import MealPlan


# class MealPlanListView(ListView):
#     model = MealPlan
#     template_name = "meal_plans/list.html"
#     paginate_by = 2


# class MealPlanCreateView(LoginRequiredMixin, CreateView):
#     model = MealPlan
#     template_name = "meal_plans/new.html"
#     fields = ["name", "date", "recipe", "owner"]
#     success_url = reverse_lazy("meal_plan_detail")

#     def form_valid(self, form):
#         plan = form.save(commit=False)
#         plan.instance.owner = self.request.user
#         plan.save()
#         form.save_m2m()
#         return redirect("meal_plan_detail", pk=plan.id)

meal_plans/templates/meal_plans/delete.html
{%extends 'base.html'%}
{% load static %}

<!DOCTYPE html>
<html lang="en">

    {%block content%}
    <div class="delete-form">
      <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ recipe }}"?</p>
        {{ form.as_p }}
        <div>
          <button class="button">Delete</button>
        </div>
      </form>
    </div>
  </main>
  {%endblock content%}

meal_plans/templates/meal_plans/detail.html
{%extends 'base.html'%}
{% load markdownify %}



  {%block content%}
  <main class="recipe-detail">
    <div>
      <a href="{% url 'meal_plans_edit' mealplan.id %}">Edit</a>
      <a href="{% url 'meal_plans_delete' mealplan.id %}">Delete</a>
    </div>
    {% if mealplan.image %}
      <img src="{{ mealplan.image }}" class="pull-right">
    {% endif %}
    <h1>{{ mealplan.name }}</h1>
    <h2>by: {{ mealplan.owner | default_if_none:"Unknown" }}</h2>
    <p>
      Created on {{ mealplan.date }}
    </p>
    {% comment %} <form method="post" action="{% url 'recipe_rating' recipe.id %}">
      {% csrf_token %}
      <div class="rating-form-grid">
        {{ rating_form.as_p }}
        <button class="button">Rate</button>
      </div>
    </form> {% endcomment %}
    <p>Tags: {% for tag in recipe.tags.all %}{{ tag.word }} {% endfor %}</p>
    {{ mealplan.description | markdownify }}
    <h2>Ingredients</h2>
    <table>
      <thead>
        <tr>
          <th colspan="2">Amount</th>
          <th>Food item</th>
        </tr>
      </thead>
      <tbody>
        {% for ingredient in recipe.ingredients.all %}
          <tr>
            <td>{{ ingredient.amount }}</td>
            <td>{{ ingredient.measure.name }}</td>
            <td>{{ ingredient.food.name }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <h2>Steps</h2>
    <ol>
      {% for step in recipe.steps.all %}
        <li>{{ step.directions }}</li>
      {% endfor %}
    </ol>
  </main>
  {%endblock content%}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}


<!DOCTYPE html>
<html lang="en">

  {%block content%}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>
  {%endblock content%}

meal_plans/templates/meal_plans/list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Scrumptious</title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
    <nav>
      <ul>
        <li>
          <a href="{% url 'home' %}">Scrumptious</a>
        </li>
        <li>
          <a href="{% url 'tags_list' %}">Tags</a>
        </li>
        <li>
          <a href="{% url 'meal_plans_new' %}">Create a Meal Plan</a>
        </li>
        <li>
          <a href="{% url 'recipe_new' %}">Write a recipe</a>
        </li>
        {% if user.is_staff %}
        <li>
            <a href="{% url 'admin:index' %}">Staff</a>
        </li>
        {% endif %}
        {% if user.is_authenticated%}
        <li>Logged in as: {{user.get_username}}</li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'login' %}">Login</a></li>
        {% endif %}
      </ul>
    </nav>

    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
    <div>
      <a href="{% url "meal_plans_new" %}">Created</a>
    </div>
  </header>

  <main class="recipe-grid">
    {% for mealplan in mealplan_list %}
      <div class="recipe-card">
        <h2 class="recipe-card-title">
          <a href="{% url 'meal_plans_detail' mealplan.pk %}">{{ mealplan.name }}</a>
        </h2>
          <p>
            {% for recipe in mealplan.recipes.all %}
            <p><a href="{% url "recipe_detail" recipe.pk %}">
            {{ recipe.name }}</a></p>
            {% endfor %}
            </p>
      </div>
    {% endfor %}
  </main>
</body>

</html>

meal_plans/templates/meal_plans/new.html
{%extends 'base.html'%}
{% load static %}
<!DOCTYPE html>
<html lang="en">


  {%block content%}
  <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
  {%endblock content%}